interface Track {
  id: string;
  title: string;
  artists: string[];
  description: string;
  creator: string;
  sellerFeeBps: number;
  referralFeeBps: number;
  previewUrl: string;
  artworkUrl: string;
  startTime: number;
  genre: string;
  explicit: "Clean" | "Explicit";
  license: string;
  initialPrice: number;
  nftAddress: string;
  marketplaceAddress: string;
}

const tracks: Track[] = [{
  id: 'the-queen-of-the-night',
  title: 'The Queen Of The Night',
  artists: ["Joe Berte' & Felipe C Feat Jadelle"],
  description: "\"The Queen of the Night\" is a captivating track that perfectly encapsulates the essence of sultry summer nights. The song features a seductive vocal performance by the lead singer, who lyrically explores the theme of fleeting romances and the allure of being desired. Her sensual voice conveys the intoxicating thrill of capturing someone's attention, making every listener feel the intensity of such passionate encounters.\n\nInterwoven between her verses are melodic riffs of accordion and saxophone, adding a rich, summery flavor to the composition. These instrumental breaks evoke the vibrant and carefree atmosphere of beachside discos, where the heat of the night mingles with the rhythm of the music. \"The Queen of the Night\" is an anthem for those spontaneous summer loves that burn bright under the moonlit sky, leaving unforgettable memories of nights spent dancing and connecting in the most electric of ways.",
  creator: "bitsong13ddj7ak2f8x6vetv67hrufsnz0ghr3e0s8c24u",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmS61x87fJotXr2GfHpG8g9m5ty2zQXD17x7cpiLnzx7eB",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmZt1aKaajYsMSBQwcQfjE59mNQa3pa7hofuXn52EePJoN",
  startTime: 1716480000,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.005265,
  nftAddress: "bitsong1pyppcutvfq3wsg2xx8zhnsfvdxjnnw4fk33r7jtwzhax9nemmxqq0hs4j9",
  marketplaceAddress: "bitsong1jhqag5ty5at3sganlw25g5pdx38vslwu8pwynsyhz9gzx7r3vhjsyrqv2a"
}, {
  id: 'vaelocity-the-purpose-of-life',
  title: 'Vaelocity - The Purpose Of Life',
  artists: ["Vaelocity"],
  description: "Utilities: \n• The first 10 holders of \"The Purpose Of Life\" will receive an NFT airdrop of the 5th song on the album \"Pain Of Letting Go\" (release on March 24); \n• The first 2 holders of \"The Purpose Of Life\" with min.30 copies collected will have a 10% share (5% each) in the royalties set of the next NFT \"Pain Of Letting Go\" (release on March 24);\n• Vaelocity is also a Mastering Engineer, so he's offering a free master of 1 song to the first 5 holders who has collected 100 copies of \"The Purpose Of Life\"; \n• After the 7 radio edit NFTs are dropped, he will drop the 7 extended edits in one DJ set (= one NFT). All holders of a radio edit NFT will get a free airdrop.",
  creator: "bitsong10wdt3z6v9kz6lmufsz8uyc557y5z9sez8spgz5",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmT7tj8UyzxfiGyCN7bwVtG4heLFAKSM5z3QNsmzJbNztU",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmPMtgmySWW7LnBkx6X8ZB5kkdLu6UNYJGhA6TCLM2LYmo",
  startTime: 1715958000,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong1jpq3ccqd5kdvxrnltzj29s2rwvzsvzrevzy29j2z968xk0zvnwrswt7ssd",
  marketplaceAddress: "bitsong16lcu6sqqjhhv3fhlurcjsm866sanenqqsad665szwg3eg03u96vs6akvts"
}, {
  id: 'love-coaster-ride',
  title: 'Love Coaster Ride',
  artists: ["Jusky & Torrex"],
  description: "Love Coaster Ride stands as a groundbreaking Dance Pop masterpiece by Jusky and  Torrrex. This track not only showcases Jusky & Torrex's exceptional talent in the realm of Dance Pop music, but it also pioneers a new era in the music industry by embracing the world of non-fungible tokens (NFTs).  “Love Coaster Ride” transcends conventional boundaries, not just in its musical brilliance but also in its approach to distribution, making it a must-have for both deep house enthusiasts and NFT collectors alike.",
  creator: "bitsong1m7wslu5cwdjyu0j83chsl9w592tq7pfqyfdwnm",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmQYUyXQCiCuXVytDVTy7T1XR9Yziw56Ddevz5YiYvtbdx",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmZw3XSFgxUdWTsQFZbVnYuc6M77HbsadBTrxD2qR4VWT7",
  startTime: 1715875200,
  genre: "Pop",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong1w73dekjygm4wwx6d8j6e4ymywzalhys77pw5a4z0gp023yu3a89sruucqk",
  marketplaceAddress: "bitsong10quspu039866w4n6v8feqd90llrmt0k8fyg9fa9d8xrsxhcd7lts27wu46"
}, {
  id: 'gone-away-again',
  title: 'Gone Away Again',
  artists: ["DJ SAVA", "ADRIANA ONCI"],
  description: "\"Gone Away Again\" unveils the latest masterpiece from the dynamic duo of DJ Sava and Adriana Onci, poised to make its exclusive debut as a music NFT on BitSong Studio on May 15th, 2024. DJ Sava, a legendary figure in the Romanian music scene, boasts an illustrious career spanning over two decades, marked by a string of chart-topping hits and groundbreaking collaborations with top-tier artists. With a penchant for crafting infectious dance anthems and soul-stirring compositions, DJ Sava has cemented his reputation as a trailblazer in the realm of electronic music, captivating audiences worldwide with his distinct sound and unparalleled creativity.\n\nIn \"Gone Away Again,\" DJ Sava and Adriana Onci bring you an amazing musical ride that'll hit you right in the feels. With Adriana's heartfelt vocals and DJ Sava's killer beats, this song takes you on a journey through all the feels – from pure bliss to deep contemplation. You'll vibe to the rhythm, get lost in the melody, and feel every emotion like it's your own. \"Gone Away Again\" isn't just a song; it's a testament to these artists' talent and passion, giving you a taste of their epic musical chemistry.\n\nThis track marks a significant milestone for DJ Sava, as he ventures into the world of music NFTs for the first time. Known for his innovative approach to music production and distribution, DJ Sava sees this digital opportunity as a natural extension of his creative journey. Just as he has pushed boundaries and explored new avenues in his music over the last two decades, DJ Sava embraces the chance to innovate in the digital realm with BitSong Studio.\n\nBENEFITS FOR HOLDERS\nRoyalties Inclusion: Holders of \"Gone Away Again\" NFTs will enjoy the opportunity to earn royalties from the song's future streaming and sales, ensuring ongoing returns on their investment.\n\nVIP Entries: NFT holders will receive exclusive VIP access to DJ Sava's live performances, concerts, and events, allowing them to experience his electrifying music firsthand.\n\nMeet & Greet: Holders will have the chance to attend intimate meet & greet sessions with DJ Sava and Adriana Onci, providing a unique opportunity to connect with the artists and receive personalized memorabilia.\n\nPrivate DJ Sets: Exclusive private DJ sets will be organized for NFT holders, offering an immersive music experience in an intimate setting curated by DJ Sava himself.\n\nAirdrops: Holders can anticipate airdrops of future releases and exclusive content from DJ Sava and Adriana Onci, ensuring they stay connected to the latest developments in their musical journey.\n\nMerchandise Discounts: NFT holders will enjoy special discounts on merchandise related to \"Gone Away Again\" and other releases by DJ Sava and Adriana Onci, enhancing their collector's experience.\n\nCommunity Engagement: Holders will gain access to an exclusive community of music enthusiasts and collectors, fostering opportunities for networking, collaboration, and shared experiences within the BitSong ecosystem.\n\nEarly Access: NFT holders will receive early access to new releases and announcements from DJ Sava and Adriana Onci, granting them insider status and priority access to limited-edition content and offerings.\n\nSpecial Wishes: Whether it's your birthday or that of your beloved ones, you can receive a private or public 'Happy Birthday' video message from the artist.",
  creator: "bitsong135rnhr7t37nq6q4u26vmk5ejvj47kl4ps5nuew",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmbJLWGyizDFKyFYaSdtHU64wpnFXyJP2Ue5DK1zUpMVow",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmQEFDedPMgNMLnMQGGngjVrMFZcHAZbeaET6tFNRq6x2L",
  startTime: 1715788800,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.02106,
  nftAddress: "bitsong194drr5fq7gs5647u3wxrndn23vxvtgknyhd2jlqp5363nj4lhqssmrgjum",
  marketplaceAddress: "bitsong1fgwwfunavcmfkskypeuzpqk4g99p55q2p5e6wvh088axczhs3ydqsjjur2"
}, {
  id: 'this-is-julian',
  title: 'Vaelocity & Julian Vaelen - This Is Julian',
  artists: ["Vaelocity"],
  description: "Utilities: \n• The first 10 holders of \"This Is Julian\" will receive an NFT airdrop of the 5th song on the album \"Purpose Of Life\" (release on March 17); \n• The first 2 holders of \"This Is Julian\" with min.30 copies collected will have a 10% share (5% each) in the royalties set of the next NFT \"Purpose Of Life\" (release on March 17); \n• Vaelocity is also a Mastering Engineer, so he's offering a free master of 1 song to the first 5 holders who has collected 100 copies of \"This Is Julian\"; \n• After the 7 radio edit NFTs are dropped, he will drop the 7 extended edits in one DJ set (= one NFT). All holders of a radio edit NFT will get a free airdrop.",
  creator: "bitsong10wdt3z6v9kz6lmufsz8uyc557y5z9sez8spgz5",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmY46XxXsYCRa22zxL1ALLSBgNHxb5QMCJXS6gcA2B73mx",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmPMtgmySWW7LnBkx6X8ZB5kkdLu6UNYJGhA6TCLM2LYmo",
  startTime: 1715360400,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.004212,
  nftAddress: "bitsong1llryyj2rravjhnpvenny2qynq5vlsakf2kzks5z5hgl49z9gptusp2jjpw",
  marketplaceAddress: "bitsong1dy7sjes0vh4cn62twhwfj98cmxdmyz4keacpgngw04rv23ypgptqg0rx6q"
}, {
  id: 'distant',
  title: 'Distant',
  artists: ["HXRT"],
  description: "'Distant' by HXRT via N43 Records",
  creator: "bitsong1l73znegcrcwsmrzs3zr8twtdmvhxcrvcx0dmez",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmeE5fRZTesaB3CU4Wd4HcfAGQ9hpPYt4NVYEWW5LDrUjV",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmRmEsDuZKehEdVGwD5h7KYWjoTLQGvvHJXMK3L6FMzV7c",
  startTime: 1715266800,
  genre: "Pop",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.013162,
  nftAddress: "bitsong12uf778e0k37gu9sa6k52fz8xgmeldhhvehy6aya37228zezenyqspnfkj4",
  marketplaceAddress: "bitsong1zw0wwunryuq5zaex6pcdphz5pxua5aevk4nqqz42hkc3xt0fcgyq09jt0z"
}, {
  id: 'vaelocity-matching-3-worlds',
  title: 'Vaelocity - Matching 3 Worlds',
  artists: ["Vaelocity"],
  description: "Utilities: \n• The first 10 holders of \"Matching 3 Worlds\" will receive an NFT airdrop of the 4th song on the album \"This Is Julian\" (release on March 10); \n• The first 2 holders of \"Matching 3 Worlds\" with min.30 copies collected will have a 10% share (5% each) in the royalties set of the next NFT \"This Is Julian\" (release on March 10); \n• Vaelocity is also a Mastering Engineer, so he's offering a free master of 1 song to the first 5 holders who has collected 100 copies of \"Matching 3 Worlds\"; \n• After the 7 radio edit NFTs are dropped, he will drop the 7 extended edits in one DJ set (= one NFT). All holders of a radio edit NFT will get a free airdrop.",
  creator: "bitsong10wdt3z6v9kz6lmufsz8uyc557y5z9sez8spgz5",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmNtqnayVG1NqQA33iJVbtKR4yg9fB5jcnD5mwmbNmJXQK",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmPMtgmySWW7LnBkx6X8ZB5kkdLu6UNYJGhA6TCLM2LYmo",
  startTime: 1714748400,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.005238,
  nftAddress: "bitsong1e0x2hnhhwyek7eq3kcxu2x6pt77wdnwz0lutz9fespdr9utq963qlmqzm3",
  marketplaceAddress: "bitsong19gmkm9fnx5s0qkc0e34kq8vd2k330j4kyrzhtxtdh3wy527qnvdsth6m8m"
}, {
  id: 'love-me',
  title: 'Love me',
  artists: ["Rawanne"],
  description: "LOVE ME transports listeners on a vibrant journey through time, blending dance and pop beats with a nostalgic nod to disco's golden era. Fusing retro influences with contemporary production, this track creates an irresistible experience that captivates audiences of all ages.\n\nBenefits for Holders:\nRoyalties Inclusion: Holders of \"Love Me\" NFTs will enjoy the opportunity to earn royalties from the song's future streaming and sales.\nVIP Entries: NFT holders will receive exclusive VIP access to Rawanne's live performances, concerts, and events.\nMeet & Greet: Holders will have the chance to attend intimate meet & greet sessions with Rawanne, providing a unique opportunity to connect with the artist.\nEarly Access: Early access to new releases from Rawanne, granting holders access to limited-edition content and offerings.\nSpecial Wishes: Whether it's your birthday or that of your beloved ones, you can receive a private or public 'Happy Birthday' video message from the artist.",
  creator: "bitsong194sk3wwncjvn0zc3sysuj3kfxaqyd4a85ks5ka",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmbxaiQydyotiSbE4fkeSWVh1s4scqcG8zAdtYVULvTyU1",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmTtBM5LxBn1LYFUkbQhYixVVjoFzGaav6JrWhc4b3qCWQ",
  startTime: 1715184000,
  genre: "Pop",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.008775,
  nftAddress: "bitsong14w9jf3vhufeeqvh6yctsdkshr5mvx3kywg5hwdrjcyp45vun0xysyfvuzs",
  marketplaceAddress: "bitsong1ajrr6m6wvk88766ampmumz39yuqhffwhq2rtp9fv257wu7l4addq24qdnj"
}, {
  id: 'saxophone-is-on',
  title: 'Saxophone is ON',
  artists: ["GROOVY LAND PROJECT"],
  description: "\"Saxophone is ON\" is the electrifying second single and debut NFT release from the GROOVY LAND PROJECT. This track is a pulsating journey through the realms of dance, where the seductive allure of the saxophone takes center stage, dictating the captivating soundscape of the dance world.\n\nWith its infectious rhythms and irresistible melodies, \"Saxophone is ON\" transports listeners to the heart of the dance floor, where every beat is a call to movement and every note is a celebration of groove. The saxophone weaves its magic throughout the track, adding layers of soulful expression and sensual energy to the music.\n\nFrom start to finish, this track is a testament to the power of music to unite and uplift, inviting listeners to lose themselves in the rhythm and embrace the joy of dance.",
  creator: "bitsong16wa7nhd7cpkkcaskz7u3snevmxz03wlm399nnn",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmZUMZerS8tuDeqzBs2juguXd3wpZh2ZxQrhc6FQbXDXAB",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmNXu7DLNb43s95fgT697UjTpPfTkhwgvnvzMWNU7vZa27",
  startTime: 1714579200,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.00351,
  nftAddress: "bitsong1qw4fh0hyd442qutcs570rs5x48nm2495aru4wgf4vd8v8rzpsz3q9g8yq8",
  marketplaceAddress: "bitsong1uzdnlhx3zcw2ak2f59vzksrv7m6egztefktxy0y8psy0lajtjjsq6890zw"
}, {
  id: 'its-your-night',
  title: 'It\'s your Night',
  artists: ["Gimmy Weaver"],
  description: "It's your night is a melodic dance record with Tony T.'s driving vocals suitable for any type of track",
  creator: "bitsong18h2flt7dhzqlnatmqlufkknm9e2g9hy60l2h6n",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmUSmuXn9jZx2V3EZLvX9pAGUMVKbjCxx53hHxHsvrEPMF",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmeCsGyPGo8rrafL9ZbGACVzPdeqSbhybH2ST8oYR2mTTy",
  startTime: 1715097600,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.005265,
  nftAddress: "bitsong1u3hacl3zu5vl7xgq9g6s8k80ava37xd3s08h24h88dmkeeqgf5nsvnxwf0",
  marketplaceAddress: "bitsong1dtzxcwfxfwpka2hst2pdct3wfd7xzlmvgqshu2eden29r2eqwvyq807qsw"
}, {
  id: 'donkey',
  title: 'Donkey',
  artists: ["Pauljey"],
  description: "Pauljey's Donkey is a bouncy record from its electronics that makes you want to turn up the volume really loud!",
  creator: "bitsong18h2flt7dhzqlnatmqlufkknm9e2g9hy60l2h6n",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/Qmein8SE4j7r2h9bpEh5jMa1aWXz5moCWpkAjiZY2sL1nG",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmQK44YzAZSv885g2ryLAaWmxggFT9wgnspYQbvt1AwqjT",
  startTime: 1714665600,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.005265,
  nftAddress: "bitsong1hm93qm43sugv9dmnqtmy680qg474t2u6cs03tmnlu5stre43tg6sdv9jwf",
  marketplaceAddress: "bitsong1s7aj6zzmr6g07zzq3lca24j4sdj85lh4j5uglt9762sn5mv03vcsr0yk7z"
}, {
  id: 'true-love-or-fantasy',
  title: 'True Love Or Fantasy',
  artists: ["Nico Del Prato"],
  description: "A unique and harmonious record a pleasant listen and an enchanting voice",
  creator: "bitsong18h2flt7dhzqlnatmqlufkknm9e2g9hy60l2h6n",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmecQAtAbF6bLRm3q6c9ZtX3eCfTGsDHXQS1hS52MYLmLS",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmUTkqunZMiV6VrNH74vs6mpSsE5oqaiqLs7K3LcgKCh1L",
  startTime: 1714492800,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.005265,
  nftAddress: "bitsong1nvnyaedrxtvhgxkdwghpr377vlg484asapf9j76pdxczw6y2dxvqs65tyc",
  marketplaceAddress: "bitsong1q9jkey9ntzked207lf7sera422z83glm77zpycg98aur6uw08dwszv6x5a"
}, {
  id: 'the-search',
  title: 'Vaelocity - The Search',
  artists: ["Vaelocity"],
  description: "The Circle Of Love is a story-telling album involving all the stages inside the phenomenon called love. The album consists of 7 storylines and 14 tracks (7 radio and 7 extended edits). First, the 7 radio edits are dropped as an NFT. A new NFT/song from the album will be dropped every week until the album is complete.\n\nUtilities: \n• The first 10 holders of \"The Search\" will receive an NFT airdrop of the 3th song on the album \"Matching 3 Worlds\" (release on March 3); \n• The first 2 holders of \"The Search\" with min.30 copies collected will have a 10% share (5% each) in the royalties set of the next NFT \"Matching 3 Worlds\" (release on March 3); \n• Vaelocity is also a Mastering Engineer, so he's offering a free master of 1 song to the first 5 holders who has collected 100 copies of \"The Search\"; \n• After the 7 radio edit NFTs are dropped, he will drop the 7 extended edits in one DJ set (= one NFT). All holders of a radio edit NFT will get a free airdrop.",
  creator: "bitsong10wdt3z6v9kz6lmufsz8uyc557y5z9sez8spgz5",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmdFz3rzQj43dZAiMkvDtnTgKME842VvaAwkeWujwfyMFL",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmPMtgmySWW7LnBkx6X8ZB5kkdLu6UNYJGhA6TCLM2LYmo",
  startTime: 1714143600,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong1p0s68cduzq40jmf3pqm4ln2669n8789rq2awz3tw5r8vhca6ykdqxfcetn",
  marketplaceAddress: "bitsong1jzl4telukvjx56l72zxuts0xm60gefgu3kla36fvfqlfxn0ckuvsys9fe3"
}, {
  id: 'sabor',
  title: 'Sabor',
  artists: ["Joe Berte'", "Adam Clay", "Paul Cam"],
  description: "\"Sabor\" is a scintillating fusion of Italian taste and Latin rhythm, crafted by the dynamic duo of Joe Berte' and PaulCam with the sultry vocals of international singers Adam Clay and Mr Don. This vibrant track ignites the dance floor with its irresistible energy, inviting listeners to immerse themselves in a whirlwind of beats and melodies.\nFrom the moment the music starts, it's impossible to resist the urge to move and groove to the infectious rhythm.\n\"Sabor\" is the ultimate anthem for anyone craving a taste of the summer spirit. So grab your dancing shoes and get ready to indulge in this electrifying musical feast!",
  creator: "bitsong18h2flt7dhzqlnatmqlufkknm9e2g9hy60l2h6n",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmeDjsRqz5ZjgVHfzvAGDvUE684bCvPmZPgGnEpA5bNBT5",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmaPmQYN4cgAAXvzd6aXaqz9q3ghUTqbStxz5ysPUgoKVV",
  startTime: 1714060800,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.00351,
  nftAddress: "bitsong1txmfsh3x38qt3fgsuthmmmqc7d96zh5k6t803fnpkm8dxa52tdhqa3medg",
  marketplaceAddress: "bitsong139pffmfeyvrrkzs6alau94x5hxl75fs3w6gyzzg6a4wqxtqnxecq3gfeey"
}, {
  id: 'gnor',
  title: 'Gnor',
  artists: ["Tava & Provenzano"],
  description: "Discover 'Gnor,' the future of electronic music! Immerse yourself in a high-energy fusion of \npulsating beats, hypnotic melodies, and electrifying drops that will transport you to a new \ndimension of sound. Get ready to dance the night away and elevate your music experience with this cutting-edge hyper house sensation.",
  creator: "bitsong1rzc9wpzh8sfjlxvarnsh7svvh4myfyd4ej2r5a",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmaoR5ogrqWyQSPV4YKSpqXJXSS51FaYn91zWS5n3CwHs1",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmU9qqkBYMa31fwa31fFmU1jBefaTSKDi98ZDaPhFQ9Sby",
  startTime: 1713970800,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.001053,
  nftAddress: "bitsong16v9et8644mhs4jwkkkhuvejjzzpuw3tnsw7x7l63sv4rx8ttq4cs7qyax8",
  marketplaceAddress: "bitsong17xwak89tznhhgrdnvxu4szcnf45tg7xjqjew6vzdezs2qlfwpk3qwekd3y"
}, {
  id: 'baila',
  title: 'Baila',
  artists: ["Stefano Pain & Trasko"],
  description: "Introducing \"Baila\" by Stefano Pain & Trasko. A mesmerizing journey through the pulsating heart of tech \nhouse music. This infectious track combines thumping basslines, intricate percussion, and hypnotic \nsynths to create an electrifying atmosphere on the dancefloor. With its seamless blend of cutting-edge \nproduction and irresistible grooves, \"Baila\" is the ultimate sonic experience for those seeking an \nunforgettable night of music and movement. Get ready to lose yourself in the rhythm and let the music \ntake control. \nThis is “Baila\".",
  creator: "bitsong1rzc9wpzh8sfjlxvarnsh7svvh4myfyd4ej2r5a",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmWXQgwDpZNXvHJ6mEwU54XobjD8MsfwFh2geqLFS9TwvT",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmbCVYLr9L4XZfYYPPrs74DaRBP6MYWDdFVKVwabpfwHeB",
  startTime: 1713884400,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.001316,
  nftAddress: "bitsong12237299f0zfntn7mqjz665l0fjq9ad2ksyn7ud9c4jsly9phr3xqycwe5j",
  marketplaceAddress: "bitsong1543sffahe5r9t28ea2h62zwy2nfq2248yavh5pt8wz6907rl63dqrma4q4"
}, {
  id: 'make-it-hot',
  title: 'Make It Hot',
  artists: ["Frank Nitty"],
  description: "Frank Nitty's latest creation blends infectious basslines, hypnotic synths, and relentless grooves, creating \nan anthem destined to set dancefloors ablaze. With his signature innovation, Frank Nitty delivers a sonic \njourney that transcends genre boundaries, inviting music enthusiasts worldwide to experience the future \nof electronic music.",
  creator: "bitsong1rzc9wpzh8sfjlxvarnsh7svvh4myfyd4ej2r5a",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmUtxAXLQFzz1gteow7EyTuebZWu1eBgCDw43tQYNsLhLV",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmXFQnPKaxEJSVZEuyuxehJF32m6VNNBW6EgiYTKcKgzBU",
  startTime: 1713798000,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.002106,
  nftAddress: "bitsong15cqej6m3wdqkde2h3x896t4e7ln8ru2xefgznvqcrx2c4cv4pljqdxj74u",
  marketplaceAddress: "bitsong1030w0x3zev3wh9u2zu2tn4sj7tcudyfauucdcvl7jz5c4x2ayfls3qztsp"
}, {
  id: 'take-me',
  title: 'Take Me',
  artists: ["AXIVER, Joseph & Baltazar, POIZZONED"],
  description: "\"Take Me\" is a techno track produced by Axiver, Joseph & Baltazar, and Poizzoned. The song features pulsating beats, intricate melodies, and a driving bassline that create an electrifying atmosphere on the dancefloor. With its seamless fusion of hypnotic rhythms and immersive soundscapes, \"Take Me\" transports listeners on a euphoric journey through the realms of electronic music.",
  creator: "bitsong1rzc9wpzh8sfjlxvarnsh7svvh4myfyd4ej2r5a",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmPSsGXwn9UFngC2CsqsGqdGLGgVLKCG3Ytk5mePmrWGJZ",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmY9VdxA3wxYdFwbaNhALQ4NcNbjaFvNwh9fYRr2mrEw12",
  startTime: 1713538800,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong17u493k974uagyay9eh97tudyygfr6qgcgfmxnzle60xerqtsdycs6n8gqg",
  marketplaceAddress: "bitsong1pcre7qn7pprvp3shncaa9lfzcen6uxwac8qynj60h9v7esrg3y0saakj5p"
}, {
  id: 'definition-of-love',
  title: 'Vaelocity - Definition Of Love',
  artists: ["Vaelocity"],
  description: "The Circle Of Love is a story-telling album involving all the stages inside the phenomenon called love. The album consists of 7 storylines and 14 tracks (7 radio and 7 extended edits). First, the 7 radio edits are dropped as an NFT. A new NFT/song from the album will be dropped every week until the album is complete. \n\nUtilities:\n\t• The first 10 holders of \"The Definition Of Love\" will receive an NFT airdrop of the 2nd song on the album \"The Search\" (release on april 26th); \n\t• The first 2 holders of \"The Definition Of Love\" with min.30 copies collected will have a 10% share (5% each) in the royalties set of the next NFT \"The Search\" (release on april 26th); \n\t• Vaelocity is also a Mastering Engineer, so he's offering a free master of 1 song to the first 5 holders who has collected 100 copies of \"The Definition Of Love\";\n\t• After the 7 radio edit NFTs are dropped, he will drop the 7 extended edits in one DJ set (= one NFT). All holders of a radio edit NFT will get a free airdrop.",
  creator: "bitsong10wdt3z6v9kz6lmufsz8uyc557y5z9sez8spgz5",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmNcK2D3sxJzCz5TTj8Sgw7bBiaCsuNRHaniGRCd9Xnedt",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmPMtgmySWW7LnBkx6X8ZB5kkdLu6UNYJGhA6TCLM2LYmo",
  startTime: 1713546000,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong12qltyf0vmpwlfn2g2ghd26uzjtfpmxu9f4fwjvgwhrk9je0xg73q3e55pj",
  marketplaceAddress: "bitsong16z0sj8fqc75gggsyjm4quajwgfg6w67z28g8sunfc0a8puxqlhvqjes886"
}, {
  id: 'break-it-down',
  title: 'Break It Down',
  artists: ["Roberto Molinaro"],
  description: "Roberto Molinaro, a celebrated Italian DJ with a career spanning from the '90s to the present day, is \nknown for his remixes and original productions in the field of dance and electronic music. Regarded as \none of the pioneers of Italian EDM, his track \"Break It Down\" takes you on a fascinating journey through \nthe depths of the downtempo genre. With a perfect blend of relaxing rhythms and hypnotic melodies, \n\"Break It Down\" is the ideal song to unwind, relax, and be carried away by its enveloping beauty.",
  creator: "bitsong1rzc9wpzh8sfjlxvarnsh7svvh4myfyd4ej2r5a",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmXoxFCYqPJH7EC7eZaZ1h1xs6EqtVEmTQR96vVH4vLnHH",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmPqwM9u8hG9EwKsGzanTmswc6JsK3fdQgZns2Z3JcTyZ2",
  startTime: 1713452400,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong14d9u3d2j7tfpj6tyfaft5a7szq2sc89dmtvfd8vfdhqct296qkeqxwcffj",
  marketplaceAddress: "bitsong1krhr0nmqhnrq9t4pkx3l8cynm5anhp7unnxz42r0zya3wass6pgqmwk6um"
}, {
  id: 'burning',
  title: 'Burning',
  artists: ["Bashment YC, Go At"],
  description: "\"Burning\" stands as a groundbreaking house masterpiece. This track not only showcases They exceptional talent in the realm of house, but it also pioneers a new era in the music industry by embracing the world of non-fungible tokens (NFTs). As the rhythmic beats and soulful melodies enchant listeners, the unique opportunity to own a piece of musical history through an NFT adds an innovative dimension to the overall experience. “Burning” transcends conventional boundaries, not just in its musical brilliance but also in its approach to distribution, making it a must-have for both deep house enthusiasts and NFT collectors alike.",
  creator: "bitsong1m7wslu5cwdjyu0j83chsl9w592tq7pfqyfdwnm",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmXe6JKEHHDAQskHkiQ1VLq1Ns1odgQpxYgEfQQ29eMHNY",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmXcDRtp6WpsUE7bs54Rw7aAa3PqAEtAvbRCvpVBLBX5F1",
  startTime: 1713366000,
  genre: "House",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong12qla58t6s4ncl7lfda6273x7lrn8xwfjn7u2yqlll6r690d9e3esusepnt",
  marketplaceAddress: "bitsong129w4tcrmzxk8u37qqtc0hezp66mkef45m3d9atnvlz09dar9a50qqvsgqf"
}, {
  id: 'all-in',
  title: 'All In',
  artists: ["HXRT"],
  description: "'All In' by HXRT via N43 Records",
  creator: "bitsong1l73znegcrcwsmrzs3zr8twtdmvhxcrvcx0dmez",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/Qmdob8QBFEsnZUECKoWN7ocyhPDXLTCyu6qCcSUoNyJhBt",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmTf7q5mQLmQE4iGnS3eazu6corap9cH52jLxMXZ7omTNX",
  startTime: 1713290400,
  genre: "Pop",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.013162,
  nftAddress: "bitsong1he85n9h0mcnzhpegj76wwcyjv626tced0zkp58wakjc7d3fm50xq0yhd4d",
  marketplaceAddress: "bitsong1wxhcewdtc8xzr6wmythx9ja8yagskgptfu6s6aa3pevzm4avgrxsljchrv"
}, {
  id: 'atom',
  title: 'Atom',
  artists: ["Alterego & Roberto Pagliaccia"],
  description: "\"Atom\" is a groundbreaking collaboration between Alterego and Roberto Pagliaccia, prominent figures in \nmelodic techno. Together, they seamlessly fuse the emotive melodies of melodic techno with captivating \nrhythms, creating a genre-defying masterpiece. This track, characterized by its celestial energy, immerses \nlisteners in a sonic vortex where cosmic melodies intertwine with mesmerizing beats. It's a musical \nodyssey that transcends boundaries, inviting listeners to explore new dimensions. \"Atom\" is a \ntransformative experience, showcasing the creative synergy of these two visionary forces in electronic \nmusic.",
  creator: "bitsong1rzc9wpzh8sfjlxvarnsh7svvh4myfyd4ej2r5a",
  sellerFeeBps: 300,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmcisLkWyR1UrKAVEB6LujydNkXGjkcQR2U7eowMLSvQUW",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmS1TB21euDpWT5mXTDPVuJ2jArvwQ4Pk6QZKRDRjTsw5j",
  startTime: 1713200400,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01033,
  nftAddress: "bitsong17v00rapt956mudlfxl3t6gf455t07y708z8vjkjfgar87q8c9vns2avy64",
  marketplaceAddress: "bitsong1s5rf2dnfmda864n6awcshv8uyx0u5hlgmv3q3e8we5665485h4lq7lpt0k"
}, {
  id: 'spacelink',
  title: 'Spacelink',
  artists: ["Alex Nocera, Roy Batti, Alex Raider"],
  description: "Introducing \"Spacelink,\" the new electronic music track created through the collaboration of talented \nartists. Alex Nocera, a renowned Italian DJ and producer specializing in electronic dance music, brings \nhis skills in crafting captivating beats and energetic atmospheres. Roy Batty, a notable Italian producer \nand composer known for his impactful Tech House tracks, adds his unique touch to the mix. Together, \nthey have created a unique sonic experience that will transport you on a cosmic journey filled with \nimmersive rhythms and evocative melodies. Get ready to elevate your minds and bodies with \"Spacelink\"",
  creator: "bitsong1rzc9wpzh8sfjlxvarnsh7svvh4myfyd4ej2r5a",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/Qme9yG4khNyVJrZuBkgccDcDYpVdFBLxtqaDsgyGh5fpym",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmdYyDENsyP3D74nrBm747oCDXTDkkQ47vJPwzTWYT6GC9",
  startTime: 1712941200,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong183u9p7k37mfwgprfj88jswehjmcl3tunrw8njdtfup6kxecf3mfsdwhmuy",
  marketplaceAddress: "bitsong1my93k4wqnexg6hrjpurfazz3mzywcctatwczvatxwyprpjralheskk7lzl"
}, {
  id: 'diap',
  title: 'Diap',
  artists: ["Tatanka & Roberto Molinaro"],
  description: "Tatanka and Roberto Molinaro are legendary djs in the electronic dance music scene. Tatanka is a true icon figure with a dedicated following and chart-topping tracks. Roberto Molinaro is celebrated for his talent, genre blending and memorable performances Their track \"Diap\" is a hardstyle masterpiece, delivering intense beats, pulsating basslines, and captivating melodies that immerse listeners in euphoria. It seamlessly blends aggressive and euphoric elements, creating an exhilarating musical experience.",
  creator: "bitsong1rzc9wpzh8sfjlxvarnsh7svvh4myfyd4ej2r5a",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmUQgXoFLCG29A4aXb4vQiFHQNxaMw7jUJwFWmqpynpqbf",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmPPFeuBEnNx7FVmhNo28cyykvDafc5hPHbN7AEfbM94KR",
  startTime: 1712768400,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong1dyesd909dxcrajgcfgvf88hwev84p02rqfqw5fpqxc6yptkwrqzsxc35sd",
  marketplaceAddress: "bitsong1e8m4dyus9zdrwe9w5fwzxv6vgnacaavjwlpr3662qg69kys8kgwqkms2c7"
}, {
  id: 'wwgd',
  title: 'WWGD',
  artists: ["Goose Pärk"],
  description: "I crafted this song in response to the pandemic, also known as the Plandemic. The overwhelming flood of misinformation about vaccines, Covid-19, and various other topics ignited my frustration. My social media accounts faced shadow banning because I exposed falsehoods with concrete evidence. Originally released in November 2020 after returning from a road trip to Los Angeles, this song serves as a testament to those who supported my previous release, “Stimulation Growth.” As a token of appreciation, those who minted “Stimulation Growth” will receive an airdrop of this song. Stay tuned for more music coming soon! In conclusion, always remember to think for yourself—it’s your strongest asset.\n\nProduced, recorded, mix and mastered by Goose Pärk. Enjoy the video as well; it was shot in Little Haiti Miami, FL. Video shot by John Atis. Edited by Goose Pärk",
  creator: "bitsong13xknrd2t5d28w3rnkly2dx3yxdwr97vhqr4z5w",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmUFKmhjicppNPRXLeMAz5RJ2i1U5nTWHheH49u1VdVdAW",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmPJtjFnm319f15Ac2U7yvh5maF7RonEdkydkdWqnzCDXu",
  startTime: 1712854800,
  genre: "Hip-Hop",
  explicit: "Explicit",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong1crdahcykk3e0nyam2vhudpm2nv0qpd7eutdkhc3658wknr5u5mhqzjvz89",
  marketplaceAddress: "bitsong1ddrly5pc0nf8dkhdvsrmy6w2d0yld2y0t0337p2zdkqajaqwas2sx2gu8g"
}, {
  id: 'we-fight',
  title: 'We Fight',
  artists: ["Alan Scarlato"],
  description: "We fight gives a message of struggle, about fighting for our dreams and objectives, something that characterizes Alan Scarlato, the track has a lot of power and is a track that fits perfectly for large festivals due to its beautiful harmony that it carries in its vocals and its great strength and energy throughout the entire song.\n\n- People who buy this exclusive NFT from We Fight will be able to contact the artist through their networks and give notice so that when we soon launch the Merchandising they will receive something unique as a GIFT at their home.\n\n- People who have obtained the NFT from Orderly and We fight will receive a double reward.",
  creator: "bitsong1ljvvxrw6cxz645mwg33gh5xny8ekwc0lsfzjsa",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmNi8qnDwKBq5GXo1qfrh3RS1X499ELet2MjfhCmFTJryZ",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmViMxhyxDJtfZYtxa6yqLQCDavwZrqeLqHGKA5rnnuRAN",
  startTime: 1712682000,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.008775,
  nftAddress: "bitsong1seeld9pqq0nxp3yt3wded4jf476y8vz77qmjj5zf8gwz3y59qu5s8dmu33",
  marketplaceAddress: "bitsong1gs5sqtyzvtf75q7zwmpmptazjpljt3r769z4ur5c4lkq46cdxucsdxmw76"
}, {
  id: 'revenge',
  title: 'Revenge',
  artists: ["Loris & Marins Feat. Dot Comma"],
  description: "\"Revenge\" is the very first release on Claw Records by the duo Loris & Marins Feat. Dot Comma , characterized by an explosive collaboration. This dance track drives with an overwhelming rhythm that captures the frenetic energy of the dance floor, while its summer flavor infuses a fresh and vibrant atmosphere. With a captivating mix of catchy melodies and pulsating basslines, \"Revenge\" is destined to become an anthem for endless summer nights and parties.",
  creator: "bitsong13ddj7ak2f8x6vetv67hrufsnz0ghr3e0s8c24u",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmXxh45aTbs8h4BRjPe7eDX3XVfupa8Q3GisG7D4bL58Dr",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/Qma8GNZ6LWXhqNbGF7zhrtbnoty6gVHaDkHjyCm6G3ywqr",
  startTime: 1712595600,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong1jmechmr7w6kwqu8jcy5973rtllxgttyetarys60rtsu0g675mkjswfpkac",
  marketplaceAddress: "bitsong1gw8ry0djv7mes2nrpp082ahu2t8xzdfrc62qxq4dpxnk0h7egnesdhm60s"
}, {
  id: 'i-got-you',
  title: 'I Got You',
  artists: ["Joe Berte'"],
  description: "First track from historic italian label Claw Records\nfounded by dj and producer Joe Berte'.",
  creator: "bitsong13ddj7ak2f8x6vetv67hrufsnz0ghr3e0s8c24u",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmQvxWs7T7MQrQ4YFPLHtCztpyyw8mTsg5UP8DcypE2yK2",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmfN1MXhZ2BFZF8EPMRy7p18KWimxjb3jHLwnDMAToeQfk",
  startTime: 1712336400,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong1kfem4ue4qn9p689ldye9t4seh077lz3ztr4zhjadxptjsaujxk5snszce9",
  marketplaceAddress: "bitsong1y7ww8whzmldvxcvcz7t6yuyel5nj7khdtews2jredfl5tjajkv3qtps9ym"
}, {
  id: 'high',
  title: "High",
  artists: ["HXRT"],
  description: "'High' by HXRT via N43 Records",
  creator: "bitsong1l73znegcrcwsmrzs3zr8twtdmvhxcrvcx0dmez",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/Qmds5W61Une4rTeEowG4UnwDvxVCxF7cBjSmENkPngQAeB",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmVk5hmF6KFE6gAgrfwmf5QFM5yJLbVButohmqs5BuqcTM",
  startTime: 1712163600,
  genre: "Pop",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.013162,
  nftAddress: "bitsong1ukhxlrtje0dt2n7k54m8l83rxjrta7fqwvzzhapgzafwzt38u8pq6pj7dq",
  marketplaceAddress: "bitsong17h0x720g7hnvtp9qyayu8hqqs5a4yxg88zdyeue9fjcpy82rvhgscer8ge",
}, {
  id: 'with-me',
  title: "With Me",
  artists: ["J Press", "Torrex"],
  description: "\"With Me\" stands as a groundbreaking Piano House masterpiece by J Press and Torrex. This track not only showcases They exceptional talent in the realm of piano house, but it also pioneers a new era in the music industry by embracing the world of non-fungible tokens (NFTs). As the rhythmic beats and soulful melodies enchant listeners, the unique opportunity to own a piece of musical history through an NFT adds an innovative dimension to the overall experience. “With Me” transcends conventional boundaries, not just in its musical brilliance but also in its approach to distribution, making it a must-have for both deep house enthusiasts and NFT collectors alike.",
  creator: "bitsong1m7wslu5cwdjyu0j83chsl9w592tq7pfqyfdwnm",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmPeoVYQYtmiwSxop1h6kg3SjM2jp3wD46rfYRfTtbRCRu",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmXJecNhzJKgyaXzWS1PCct3WbJMt2S6qcLj6gx4yRGNRs",
  startTime: 1711735200,
  genre: "House",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong1quce89l8clsn8s5tmq5sylg370h58xfnkwadx72crjv90jmetp4sm9de2c",
  marketplaceAddress: "bitsong1l9mw4azn0k7f9qrx6r49cyke7trpv52t5pl4363ptglzl8nmm5tqzgkjpe",
}, {
  id: 'up-funk',
  title: "Up Funk",
  artists: ["Torrex"],
  description: "\"Up Funk\" is an electrifying Funky Groove House track that transports listeners to the pulsating rhythms of the dance floor. Produced by the talented DJ/producer Torrex, this dynamic composition seamlessly blends the infectious beats of House with the vibrant essence of Funk music. The track's title, \"Up Funk\" reflects its rhythmic cadence that invites the audience to move in unison. Released as an exclusive NFT by the esteemed Italian record label Semantic Sounds, this musical gem not only captivates the senses but also marks a groundbreaking intersection of electronic music. \"Up Funk\" is not just a track; it's an immersive experience, a testament to the innovative spirit of Torrex and the forward-thinking approach of Semantic Sounds.",
  creator: "bitsong1m7wslu5cwdjyu0j83chsl9w592tq7pfqyfdwnm",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmWheUwaN3ao9TqLGpLCfNdaB1eeXEob5A8624xUBZrJkY",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmQGKBtyGg2xFS26qoVYCSewGtdkdtVg2asTRrxzRX1xXV",
  startTime: 1711648800,
  genre: "Funk",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong1taerpmv0tzdrnls7z567khds88fwfpdaeeg7s0wkel9zjap7gnesxnsv6c",
  marketplaceAddress: "bitsong1qdh2egr3aneuvqf6mruxzjwxjw8splnv6shzzlm3kwsdrd0xpzkspp56sd",
}, {
  id: 'i-want-to',
  title: "I Want To",
  artists: ["Alpaca", "Dario Denso"],
  description: "\"I Want To\" is an exclusive project that combines the sound of Alpaca with the visual arts of Dario Denso Andriolo. It is a multisensory experience that blends drum & bass with low ambient breakdowns, enriched by the interaction between digital instruments, synthesizers, and vocals. \nThrough its pulsating rhythms and ethereal pauses, this track transports the listener on a journey to an unknown world, between Blockchain and the Metaverse.\n\nIn this NFT, 3D scans of real models, ordinary men and women, are presented, whose anatomical details are intentionally blurred almost as if to remove identity from the subjects. These individuals are dressed, in addition to the typical intangibility of religious representation, in original patterns that decorate their bodies like giant tiles extracted from the Sicilian Reflection exhibition.",
  creator: "bitsong1rtrd00hk5up3uc0nttxkutena56sywy0vae44s",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmXwUhQTnVhJN1An7rXJGzHkWUmAGK4nJz3F4r6KBFXBEf",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmPs61TrrSyjvTZeuPsHKUY8MNiAXkTH196CQprdumhp92",
  startTime: 1711130400,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.013162,
  nftAddress: "bitsong13xww866f545ackl0004tm94jdh5y7hht5rjnpejktyw4nqkvrxtswkmt53",
  marketplaceAddress: "bitsong1478sh2c7xgk2xufh32l3p4vsyeyd5xemqm6f2jrwz39wa9atgkpsvzchzq",
}, {
  id: 'spicy',
  title: "Spicy",
  artists: ["J Press"],
  description: "\"Feeling”Good stands as a groundbreaking Tech house masterpiece by Torrex, J Press, and Deviless. This track not only showcases They exceptional talent in the realm of Tech house, but it also pioneers a new era in the music industry by embracing the world of non-fungible tokens (NFTs). As the rhythmic beats and soulful melodies enchant listeners, the unique opportunity to own a piece of musical history through an NFT adds an innovative dimension to the overall experience. “Feeling Good” transcends conventional boundaries, not just in its musical brilliance but also in its approach to distribution, making it a must-have for both tech house enthusiasts and NFT collectors alike.",
  creator: "bitsong1m7wslu5cwdjyu0j83chsl9w592tq7pfqyfdwnm",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmX7jK26yKGHFrebwgyCv6KgZ6zvrkPwU33UbRZoR6w3Lb",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmQpN2HN6HECMEo7WrWcrR2dtyMZwCGfRqn2hFveo5tRMc",
  startTime: 1711044000,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong1s84uvkzuz7tlyykp587aynn8xr0m6t5r64lz6pkfyzyrhzaezhrszhwyz5",
  marketplaceAddress: "bitsong1lpxsk8a8dxdpy8r6yqlz0gmjc7427wg9h25sj46c8d6jaglmzxsqgujlmn",
}, {
  id: 'feeling-good',
  title: "Feeling Good",
  artists: ["Torrex, J Press & Deviless"],
  description: "\"Feeling”Good stands as a groundbreaking Tech house masterpiece by Torrex, J Press, and Deviless. This track not only showcases They exceptional talent in the realm of Tech house, but it also pioneers a new era in the music industry by embracing the world of non-fungible tokens (NFTs). As the rhythmic beats and soulful melodies enchant listeners, the unique opportunity to own a piece of musical history through an NFT adds an innovative dimension to the overall experience. “Feeling Good” transcends conventional boundaries, not just in its musical brilliance but also in its approach to distribution, making it a must-have for both tech house enthusiasts and NFT collectors alike.",
  creator: "bitsong1m7wslu5cwdjyu0j83chsl9w592tq7pfqyfdwnm",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmeUTTZBsoR9HoTzujGionEtSbmKdvisV4xQvWje9kTMky",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/Qmf1KLZF1TWums7VYMzg8Ark8cU2XhX91yNzoj5kGFXMX2",
  startTime: 1710957600,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong19vxp8vq8qm368dr026qxh8v82satwaf79y235lfv6wmgpwxx8dts2dftve",
  marketplaceAddress: "bitsong1h7aw6rca4l6ykxkugr5lujadpnkc5wemr7xjmzt76ymjn05pcamspmus09",
}, {
  id: 'closer',
  title: "Closer",
  artists: ["Florin Dumbraveanu"],
  description: "My journey of NFTs on BitSong Studio continues, and I couldn't be more thrilled to introduce my latest creation, \"Closer\".\n\n\"Closer\" is a deep house track, filled with melodic vibes and beautiful touches of female vocals. It's all about taking you on a journey, one beat at a time.\n\nWhat makes \"Closer\" so special?\n\n1. 10 lucky Collectors of \"Closer\" will receive an airdrop of my next release. It's my little way of saying thank you for your support\n2. Two Collectors of \"Closer\" (min.20 copies collected) will have a 10% share (5% each) in the royalties set of one of my upcoming releases. Your support means the world to me!\n3. Are you an artist? Let's collaborate! I'm offering the chance to feature your unreleased tune and launch it together as an NFT and on DSPs with my record label, 404 Deep Records.\n4. As if that wasn't enough, one lucky collector (minimum 40 copies collected) will win a physical vinyl of \"Closer\" through a random drawing.",
  creator: "bitsong1mvqdh3mkc9vaqr5394tkkef08jcnndcernl54j",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmbtPmLQQeSJmWtXiZs3CsqcbqDbEykMLf1ggpnFtt2XK2",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmdbSuJW3a1xWoLgPosaKkKW3ihSGKDWuXVMNQNsyUXr4W",
  startTime: 1710525600,
  genre: "House",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.0351,
  nftAddress: "bitsong1lgprt38gkp4nvggjl0dm0e7k5lgd80e525f8rjg60tc6fk2xexcqad682u",
  marketplaceAddress: "bitsong1z2wr8jmxmpe8x3j25rl8360pfl4w9p3ry3dpss90yuek4je4wgxq45hq44",
}, {
  id: 'casanova',
  title: "Casanova",
  artists: ["Campoli", "Adam Clay"],
  description: "\"Casanova\" - a red-hot collaboration between Adam Clay and the young, talented Italian DJ, Alessio Campoli. With its irresistible blend of spicy lyrics and infectious beats, this track embodies the essence of the legendary Italian Latin lover.  The groove of the track is anchored by a thick, groovy bass line that sets the perfect foundation for Adam Clay's smooth rap delivery, punctuated by bursts of horn section that add an imperial and pompous riff, elevating the chorus to new heights. \nFrom the moment the music starts, you're transported into a world of pulsating energy and undeniable charm. \nGet ready to dance and feel the heat with \"Casanova\"!",
  creator: "bitsong1f5ze3svwg8fgjuwwnr743j6fr9vtyr58nex7tu",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmXrW1iLUX8eGYpNdUUKMvBmh1PMft6jyVuGqSV7Ho21ge",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmUeYQ7cFWdzNoVckpXnNtWBobNUiYieUNGLKtp1VQ9isS",
  startTime: 1710439200,
  genre: "Dance",
  explicit: "Explicit",
  license: "All Rights Reserved",
  initialPrice: 0.02106,
  nftAddress: "bitsong1fdtlnwuqwp38tq5ky5g3xfkkafexa4e8q4qy90jxe2vmtl8n56ksjpjhxs",
  marketplaceAddress: "bitsong1ncqsywt37u5utre8f9maptwn6fm6378lfs8avg9zl6qj73x2adgqyppade",
}, {
  id: 'anything-i-do',
  title: "Anything I Do",
  artists: ["BlackJack", "Hamster NFT"],
  description: "In a mesmerizing blend of digital art and music, composer Tulea BlackJack partners with Hamster NFT to unveil \"Anything I Do,\" a groundbreaking video that merges NFT art and melody.\nThis collaboration brings to life a narrative set in a vibrant club scene, accentuated by BlackJack's emotive music, which captures human emotions.\n\nThe video unfolds in a neon-lit club, brimming with energy, where a DJ, inspired by BlackJack, spins tracks that fill the space with a captivating rhythm. Amidst shadows and light, each musical beat echoes the pulse of the night.\n\nCentral to the story are digital hamsters crafted by Hamster NFT, symbolizing love in the digital era. With vivid animations, they navigate the club, reflecting the lyrics' exploration of love, longing, and the pursuit of connections amidst life's fleeting moments.\n\nJoin our digital journey with Tulea BlackJack and Hamster NFT. Spin the digital wheel and explore the boundless creativity of NFT art and music!",
  creator: "bitsong1w35ntzzkf7dugwlq5a6lhrrp2lkq6yamxk42he",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmSC6HrG9mLZDwtPYdF88ihdzcLEZAuQf63FY7Wmripj3R",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmcwP241RSACz8LcZy8ms49TSpgGheq8ejRHPsXRaJZDwP",
  startTime: 1710352800,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.01053,
  nftAddress: "bitsong1hje6ecs6u683ypnzu8l5d4jsxq4dy96s0m6ezps9uwcuwl30hfuqk95jqe",
  marketplaceAddress: "bitsong1csgj9nugf2dgq2hu4zmm3986ss038ehr3c82ty6hr00drh37peus8facz4",
}, {
  id: 'mexico-bailante',
  title: "Mexico Bailante",
  artists: ["Torrex"],
  description: "\"Mexico Bailante\" is an electrifying Latin Tech House track that transports listeners to the pulsating rhythms of the dance floor. Produced by the talented DJ/producer Torrex, this dynamic composition seamlessly blends the infectious beats of Tech House with the vibrant essence of Latin music. The track's title, \"Uno Dos Tres,\" reflects its rhythmic cadence that invites the audience to move in unison. Released as an exclusive NFT by the esteemed Italian record label Semantic Sounds, this musical gem not only captivates the senses but also marks a groundbreaking intersection of electronic music. \"Mexico Bailante\" is not just a track; it's an immersive experience, a testament to the innovative spirit of Torrex and the forward-thinking approach of Semantic Sounds.",
  creator: "bitsong1m7wslu5cwdjyu0j83chsl9w592tq7pfqyfdwnm",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmZxDxSroSwfPkDcRcdtyNponqV1qNjfQbWpEZn4X6iiJk",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmNQBCwB6nshni2vpdpC1VNoMnEDjByM3RGxz6UWgL3Brf",
  startTime: 1710266400,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.02106,
  nftAddress: "bitsong1aqjn8sha92zyqd27d4gw8lnjgmgt24v3ytwm2f9j9rza7pfuku4s7ej6r7",
  marketplaceAddress: "bitsong1x4kzffnyd7jkldual9xkp2hu22g5vs0k8kuw847mtkevs8pcec5sarl6d9",
}, {
  id: 'famous-girl',
  title: "Famous Girl",
  artists: ["J Press"],
  description: "\"Famous Girl\" stands as a groundbreaking Tech house masterpiece by the renowned DJ/producer J Press, and it marks a significant milestone as the inaugural release from Semantic Sounds, an italian record label founded by djs/producers Torrex & J Press, available as an NFT on bitsong.studio. This track not only showcases J Press's exceptional talent in the realm of Tech house, but it also pioneers a new era in the music industry by embracing the world of non-fungible tokens (NFTs). As the rhythmic beats and soulful melodies enchant listeners, the unique opportunity to own a piece of musical history through an NFT adds an innovative dimension to the overall experience. \"Famous Girl\" transcends conventional boundaries, not just in its musical brilliance but also in its approach to distribution, making it a must-have for both deep house enthusiasts and NFT collectors alike.",
  creator: "bitsong1m7wslu5cwdjyu0j83chsl9w592tq7pfqyfdwnm",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmZmXu9u2jkWg5A3f1GE1Td7q3N3adAoWNfw5HzbbpJsp3",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmZrLNcJVx4s9MNjK2dwW55iXrxnD1KFZ8knbehXJQFzFE",
  startTime: 1710180000,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.02106,
  nftAddress: "bitsong1jeh4eqlsge0w8kcmjlt82rzzwe4vr5yxe69nvqt2jcgg4q4e8ypq9592yw",
  marketplaceAddress: "bitsong1a0ym9flprpmfzzeek3ensut2tlkzltre4yyp3hy0ttwu05jhunyswzx6d3",
}, {
  id: 'all-i-need',
  title: "All I Need",
  artists: ["Lollino & Deebesh"],
  description: "Lollino, an experienced DJ from Turin, has been a prominent figure in the music industry for nearly two\ndecades. He has graced the decks of top clubs worldwide. Joining him is Deebesh, a DJ and producer from Savona, now based in Turin. Their collaboration gave birth to \"All I Need,\" a cutting-edge tech house track with underground vibes and futuristic sounds. Featuring a heavy bass line, mesmerizing synth, and dynamic drums, this track is primed to ignite dancefloors at clubs and festivals.",
  creator: "bitsong1rzc9wpzh8sfjlxvarnsh7svvh4myfyd4ej2r5a",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmXXibPrZqtXAqbz1BS8JDVqqMyfkkStGdoRrBkkXZqCrv",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmSvWAqpea6xZT8z2tzZeLCS9hxEfePkGLq2qju7kzL3cp",
  startTime: 1709920800,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.02106,
  nftAddress: "bitsong1kg02jufkxt6znuv2r96nkpdc7nxdlfeznaz7gfyj6449x6tle2ksyyxt6n",
  marketplaceAddress: "bitsong10l67n20j7cjxu83a6yrdyqqln6mrcq3844c3wccr7qk0vn5j0laq4jvsd4",
}, {
  id: 'secrets',
  title: "Secrets (Feat. Eli Limaj)",
  artists: ["Noyse, Zangi"],
  description: "Noyse, a renowned DJ and producer from Ferrara, Italy, made his debut in 2016 and captivates unforgettable musical experience.\n audiences with his skillful fusion of Tech House, Future House, and Electro House. Zangi, a talented Italian DJ since 2010 and producer since 2019, dedicates himself to creating dance tracks that evoke emotions in the audience. Together with Eli Limaj, an American singer-songwriter and music producer who finds freedom in songwriting, they collaborated to create \"Secrets\". It is a captivating slap house/chill house track that combines catchy melodies and engaging rhythms, creating a unique and immersive atmosphere. This enchanting composition invites listeners to dance and immerse themselves in an unforgettable musical experience.",
  creator: "bitsong1rzc9wpzh8sfjlxvarnsh7svvh4myfyd4ej2r5a",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmZhYuQHAW2JSbLzxAFEYjwMojibKbbgRGnnb54fF4f1gQ",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmTPzYSevY31hX6Dy6nAXrBz5cBpMjLFRoc1JKk1FzFnDc",
  startTime: 1709834400,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.02106,
  nftAddress: "bitsong1sj7zrll8n6rh07hgzqtjemeeane53a68fzqzsmnyntw95w4h7z6sfjk6ht",
  marketplaceAddress: "bitsong1etks7y0srjrkgrx5cs7rsw89txw6xrkcrkknyyqa6ppaau03f25set8882",
}, {
  id: 'wind-still-blows',
  title: "The Wind Still Blows",
  artists: ["Kiras"],
  description: "“The Wind Still Blows” is the first NFT by electronic music producer Kiras (Italy). This is a mind blowing 4 minutes and 360° sensory evolution A/V artwork. Surreal and fairy electronic music, an enchanted and dreamlike artwork with a constant emotional rise until the last second. \nSound design flow is melted with the visual concept created by Irene Canali (Italy).",
  creator: "bitsong1hf35lrmjtny9d4cmdg3k006wvwmrapu6wksyka",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmVbifUVPA4xpeM8972sSaEDYfagr2RNyFhqboyQrVkEvd",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmPCoexML73gyABtNfJthK2qMwpLqF5Q5F2scS9jr6qVtS",
  startTime: 1709661600,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.02106,
  nftAddress: "bitsong18dhyf7sdkjpmgu4jg6fmf4d6cyj9lez6c2cs5lvprkmyctfrtnzq94q0l6",
  marketplaceAddress: "bitsong1mpyp9t48q2dy6s4lkxwjpy8sgg4r823hwam2tap2ra86hmgrrqyq559dcc",
}, {
  id: 'all-i-want',
  title: "All I Want",
  artists: ["J Press"],
  description: "\"All I Want\" stands as a groundbreaking deep house masterpiece by the renowned DJ/producer J Press, and it marks a significant milestone as the inaugural release from Semantic Sounds, an italian record label founded by djs/producers Torrex & J Press, available as an NFT on bitsong.studio. This track not only showcases J Press's exceptional talent in the realm of deep house, but it also pioneers a new era in the music industry by embracing the world of non-fungible tokens (NFTs). As the rhythmic beats and soulful melodies enchant listeners, the unique opportunity to own a piece of musical history through an NFT adds an innovative dimension to the overall experience. \"All I Want\" transcends conventional boundaries, not just in its musical brilliance but also in its approach to distribution, making it a must-have for both deep house enthusiasts and NFT collectors alike.",
  creator: "bitsong1m7wslu5cwdjyu0j83chsl9w592tq7pfqyfdwnm",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmcHotd42aAo9dS69MtJy6287TEoofXWsCU7YBsaLSUhm9",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmdKJA6PG55qc3Hbe9Qp8njFjtc8MxMkkU8buvhZUr3shj",
  startTime: 1709575200,
  genre: "House",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.02106,
  nftAddress: "bitsong1dhmd8lredr9psu4afk8j3lstdg896pme49mje6maxucuuugmmptspwx04e",
  marketplaceAddress: "bitsong1naazzhhz5k92m26ap6phqmht5d8js52mg9uke2wynenqzzn6s63qej43gn",
}, {
  id: 'feel-the-vibe',
  title: "Feel The Vibe",
  artists: ["Dino Brown", "Adam Clay"],
  description: "Embark on a pulsating journey into the heart of rhythm with 'Feel the Vibe,' a dynamic electro-tribal anthem brought to life by the visionary collaboration of Italian DJ and producer Dino Brown and the internationally acclaimed songwriter, Adam Clay. This electrifying track ignites the senses with its infectious beats and hypnotic melodies, seamlessly blending Dino Brown's signature soundscapes with Adam Clay's evocative lyricism. \n\n'Feel the Vibe' is more than just a song; it's an invitation to immerse oneself in the collective energy of the dance floor, to lose oneself in the primal pulse of the music, and to experience the transformative power of rhythm and movement. With Dino Brown and Adam Clay at the helm, this electrifying collaboration promises to ignite dance floors worldwide and leave an indelible mark on the hearts of all who surrender to its infectious energy.",
  creator: "bitsong18h2flt7dhzqlnatmqlufkknm9e2g9hy60l2h6n",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmYj23wu43z3knqkxPAwtvWxr2kBaD94wKbEEbKdPkanRx",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmRWZFsYP9m1eQeSooSSk72hBwECLy11U7RvR6mZGuUEKS",
  startTime: 1709316000,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.02106,
  nftAddress: "bitsong156x86uprzaj04v7qwnpl8djj5jws3gn73jz08qkydmkd0c0lp6gqn6xarq",
  marketplaceAddress: "bitsong1w2l4w5p66l5t2nmrmsvz7k4cu50s7e8dc6h59gcxsnmp2tgy7q7sh5zj0r",
}, {
  id: 'glory',
  title: "GLORY",
  artists: ["Triplo Max"],
  description: "I'm thrilled to introduce \"Glory,\" my latest house music track that's all set to take you on a cosmic journey of inspiration and energy. Drawing from the vastness of the universe, \"Glory\" infuses deep gospel voices and beats to ignite your soul and fuel your motivation.\n\nThis is just the beginning of my NFT venture, and \"Glory\" marks the Genesis NFT exclusively launching on BitSong Studio. You won't find it anywhere else!\n\nAs the holder of \"Glory,\" you'll enjoy exclusive perks and VIP treatment, including:\n\n- Airdrops of my upcoming releases\n- Random draws to share in the royalties of some of my future releases on BitSong Studio\n- Opportunities for collaborations with me\n- VIP access to my real-life events through random draws\nAnd that's just the beginning!\n\nDon't miss out on the chance to own a piece of my musical journey and unlock unforgettable experiences with \"Glory.\"\n\nCatch you on the cosmic beats!",
  creator: "bitsong1rztprdvx003fj6gtwtwum5jw62capvsmyxercf",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmWMKEpXXtPpfLuPfBR84gLiLVV8egLQPKVRk5RGPobdVt",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmRpEuACERGTLctqQaAjiPfQnj8XrzUkF8o6rmLLhCvSzg",
  startTime: 1709229600,
  genre: "House",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.053,
  nftAddress: "bitsong1kjmzvl2us872qverxre5shu747zsx4rh0xp58l4hx838ck7zcp0qzww59y",
  marketplaceAddress: "bitsong19cq5ladm6mxu8clszem8d8cwj9haac4du08s5zq2uvpyg4ue625ql4nskw"
}, {
  id: 'destructure',
  title: "Destructure (Feat Gab3z)",
  artists: ["Luca Testa"],
  description: "Luca Testa, the internationally acclaimed DJ and producer from Turin, delivers high-energy hardstyle\ntracks that push boundaries and make a lasting impact on the electronic music scene. His collaboration with Gab3z, “Destructure\", combines powerful beats, aggressive bass lines, and catchy female vocals, infusing hardance influences for an intense and mesmerizing musical experience. Surrender to the infectious rhythms of \"Destructure\" and unleash your energy on the dance floor.",
  creator: "bitsong1rzc9wpzh8sfjlxvarnsh7svvh4myfyd4ej2r5a",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmeCPPUvcRKGyps6vCiQSAwFngWXbKTiT9Mgx3M35vLNVp",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmPSq8vYWJ1ALdjBAyju2Gb2yyUoXHwpLwxVoyFrUjVa52",
  startTime: 1709143200,
  genre: "Electronic",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.02106,
  nftAddress: "bitsong1l0z6d7wlwpwequtenwt8pd44685jyhqys6jdnp8xa8ektn0un4zshplnar",
  marketplaceAddress: "bitsong1fur82ejcye82qqeah83v2tndt2m2l3y0ceypdkxe50rl0jj8xxysr0ldqf",
}, {
  id: 'uno-dos-tres',
  title: "Uno Dos Tres",
  artists: ["Torrex"],
  description: "\"Uno Dos Tres\" is an electrifying Latin Tech House track that transports listeners to the pulsating rhythms of the dance floor. Produced by the talented DJ/producer Torrex, this dynamic composition seamlessly blends the infectious beats of Tech House with the vibrant essence of Latin music. The track's title, \"Uno Dos Tres,\" reflects its rhythmic cadence that invites the audience to move in unison. Released as an exclusive NFT by the esteemed Italian record label Semantic Sounds, this musical gem not only captivates the senses but also marks a groundbreaking intersection of electronic music. \"Uno Dos Tres\" is not just a track; it's an immersive experience, a testament to the innovative spirit of Torrex and the forward-thinking approach of Semantic Sounds.",
  creator: "bitsong1m7wslu5cwdjyu0j83chsl9w592tq7pfqyfdwnm",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmWycYBJAPTsHSTx8FYbaexAL6x588iec94WUbEN9HBCTi",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmXVXMo3TESkYnXbR8zb1kBeRRtRhYkTDK9T9uFjoTBdjo",
  startTime: 1709056800,
  genre: "House",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.02106,
  nftAddress: "bitsong1r8td9cjggx9f5ek2gzfh34kguxuz5j9rfjemamvjw2he2y84t3xqp9vgyz",
  marketplaceAddress: "bitsong1dc032y7cjml3uddygdnpk54e6h4vfzrl24w7pk75d7gxf98x778s9qdysw",
}, {
  id: 'supreme-forces',
  title: "Supreme Forces",
  artists: ["House Of Disaster"],
  description: "\"Supreme Forces\" by House Of Disaster is a groundbreaking orchestral masterpiece tailored for the cinematic landscape of Web 3.0. This symphonic marvel transcends sound, immersing listeners in realms of emotion and grandeur. With resounding notes and sweeping crescendos, House Of Disaster crafts a sonic tapestry that captivates the soul. In an era of digital innovation, they push boundaries, reaffirming mastery while redefining cinematic soundscapes. Step into this auditory realm to experience the sheer power and majesty of House Of Disaster's artistry, elevating storytelling with each note.",
  creator: "bitsong14r978dkxftm36s7a02g6p2xvvypykq376scn9w",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmPd25EnJo3grbwJywXPDNyyY6VCrqMNXuHCtrsPQczMk3",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmbaW1vD8cYCtGLWxfyS4cbCCnj5fHewXnMA46mC8JC9UY",
  startTime: 1708682400,
  genre: "Classical",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong1hdnu502uecmddk9w48kxvekgp43mjdpr3mza9kj2tfvjpgef5grs2t5qp5",
  marketplaceAddress: "bitsong17w9r23r8v8r7z5lphwj99296fhlye9ej5nq3hlqw554u63m88avszxp3rx",
}, {
  id: 'pure-madness',
  title: "Pure Madness",
  artists: ["H.O.D.E."],
  description: "Prepare for an electrifying journey into the heart of techno with H.O.D.E.'s latest track, \"Pure Madness,\" designed specifically for the dynamic realm of Web 3.0. This pulsating anthem immerses listeners in a whirlwind of driving basslines and infectious melodies, igniting an atmosphere of sheer energy and excitement.\n\nAs trailblazers in the techno scene, H.O.D.E. defies conventions with \"Pure Madness,\" delivering an auditory experience that pushes boundaries and leaves an indelible mark. With their unparalleled production prowess and astute grasp of the evolving digital music landscape, H.O.D.E. creates a sonic masterpiece that transcends the ordinary.\n\n\"Pure Madness\" isn't just a song; it's a bold statement heralding the future of electronic music in the digital age. Brace yourself for an exhilarating sonic adventure that will redefine your perception of techno.",
  creator: "bitsong14r978dkxftm36s7a02g6p2xvvypykq376scn9w",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmTJNydGV1Eoc2EJjY964jYpYrwhFTQWrPZzboHcuFEtap",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmNiDzBVHQKaFn3MiyN4QdeMpsNzUd2G1oLodD5S3Njkp6",
  startTime: 1708621200,
  genre: "Techno",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong1cv5er0wsla3u33w6rkn7ckxpn88huqh9aw0xpu0pagksege7v7nssqvs3x",
  marketplaceAddress: "bitsong1w4t2qpwvhyhz0g2mwgqjzgsw63dcy5hkfch0tgr8xj9qjcsauq8qhd3kwu"
}, {
  id: 'ethernal-darkness',
  title: "Ethernal Darkness",
  artists: ["House of Disaster"],
  description: "\"Eternal Darkness\" by House Of Disaster, a captivating orchestral masterpiece marking their entry into Web 3.0 music. This composition embodies grandeur and emotive depth, crafting a vivid sonic landscape that transports listeners to enchanting yet foreboding realms. House Of Disaster's meticulous orchestration invites audiences to immerse themselves fully, evoking lingering emotions and imagery. With haunting melodies and thunderous crescendos, \"Eternal Darkness\" showcases their commitment to pushing cinematic music boundaries in the digital era. Notably, this track has garnered numerous awards at international festivals, solidifying their talent and global recognition. Brace yourself for a symphonic adventure of transformative allure.",
  creator: "bitsong14r978dkxftm36s7a02g6p2xvvypykq376scn9w",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmZo7ixiSmt1kahp1s1NaokLdCxgVMKN9otVZjo1pUXaFj",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmUNf866qqVnoxA5bQXXzsFkGs9KM79UHL3w2GiDUtZX6o",
  startTime: 1708596000,
  genre: "Classical",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong1w9udhqtvuefwfmx7af9qe5jjhmrjk4p7ezxm6py08puykgen6uhqk8nxyh",
  marketplaceAddress: "bitsong1hs95lgvuy0p6jn4v7js5x8plfdqw867lsuh5xv6d2ua20jprkgesdplg64"
}, {
  id: 'out-of-web',
  title: "Out of Web (3.0)",
  artists: ["The Genesis Projection"],
  description: "\"Out of Web (3.0)\" by The Genesis Projection marks their triumphant entry into the realm of Web 3.0 music. Released under their new label, Sound Core Picker, this hardcore track showcases the band's evolution with a powerful and revitalized sound. Building on years of success with Dutch labels, the song is a fusion of relentless energy and uncompromising intensity. It signifies the band's commitment to pushing boundaries and embracing innovation in the digital music landscape. \"Out of Web (3.0)\" invites listeners on a thrilling sonic journey, promising to captivate and exhilarate with its raw, unbridled force.",
  creator: "bitsong14r978dkxftm36s7a02g6p2xvvypykq376scn9w",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmYnPpRMR3uJsa61b5LswzjkYUvNaPNxPRSZMesqcERdaH",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmYmGZ4zr8mbopBp4Hm2EDPtbMjQR75H8mk1iG97EjeNbA",
  startTime: 1708491600,
  genre: "Techno",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong1xq7yffwchsu2ldw3lukgzcncryva7wt35gv9cr59wt6ts2ktknwqt6atp0",
  marketplaceAddress: "bitsong1jg5y3m2u9ac50g5jsd7mksh3y9nvp3pyuf5fj8entsk9tv2tq4gshdksnk"
}, {
  id: 'under-pressure',
  title: "Under Pressure",
  artists: ["H.O.D.E."],
  description: "\"Under Pressure\" by H.O.D.E. (Sergio Mitrione), part and producer of The Genesis Projection, is a pulsating techno track that delves into relentless energy and tension. With pounding beats and hypnotic rhythms, it immerses listeners into a world of urgency and anticipation. Skillfully manipulating soundscapes, H.O.D.E. showcases versatility and innovation, solidifying his status as a dynamic force in electronic music. This track serves as a testament to his mastery of sound and his ability to push boundaries within the genre.",
  creator: "bitsong14r978dkxftm36s7a02g6p2xvvypykq376scn9w",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/Qmdpf9r8cxiTPvei1WKyUSybZvw2b5MEbBvJfBBoRYgenK",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/Qmb74GezcrGpucDDank3WE8HEQVLDFfTAyea2jmbJz2Lct",
  startTime: 1708192800,
  genre: "Techno",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong1pcmlq5cwmy9lxfhynnuhd0r2djm2xn3ff2xc6njncs8sxzlgle3s06wsc8",
  marketplaceAddress: "bitsong1xmehyq3tkcyxr0ppgce67rr7cfcpf9qqpll3ykfcqqd0f2xznkdsgtlu5w"
}, {
  id: 'need-backup',
  title: "Need Backup",
  artists: ["Florin Dumbraveanu"],
  description: "Introducing \"Need Backup\", an electrifying Deep House track launching exclusively as an NFT on BitSong Studio! 🎵\n\nImmerse yourself in the pulsating rhythms and infectious energy of this captivating tune. Featuring the iconic \"need backup\" sketch from the Counter Strike video game, the track transports you into the heart of the action, where every beat echoes the intensity of the battlefield.\n\nSupport my music on BitSong Studio and I'll take care to give you exclusive benefits in the future and I'll also share my royalties with y'all once the referral system is being implemented on the Studio!",
  creator: "bitsong1mvqdh3mkc9vaqr5394tkkef08jcnndcernl54j",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmewD9aKrXavCMhbgZDP4wpywYwAjfGrsBdjP5t38gSuEk",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmeZqmGpw2BD6mtVAPFmjSZ2ypas4iB3rqHLZnPqWWfaRR",
  startTime: 1708020000,
  genre: "House",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong14tccd5wwd6ygwtx67xdfpzz8xn8ysd3rkmkd3pj326l2v7asjr6qxgf7gr",
  marketplaceAddress: "bitsong1v8lkqws3gd6npr0rdk9ch54amh9guas86r4u62jq27hee88lryfs99achg"
}, {
  id: 'on-the-fly',
  title: "On The Fly",
  artists: ["Joe Mangione"],
  description: `“On the Fly” is a track that pulses with the vibrant energy of tribal house, a genre renowned for its potent rhythms and capacity to ignite dance floors. As the beat rolls forward, a series of chopped vocals enter, each snippet carefully sliced and interwoven into the fabric of the instrumental. These vocal cuts are not mere accents; they are integrated as percussive elements, adding layers of rhythm upon the already irresistible core beat. They echo and reverberate, mimicking the call and response of tribal gatherings, and serve to deepen the connection between the music and the primal urge to move. A rhythmic fusion, where every beat, every vocal chop, every rise in tempo is meticulously crafted to ensure that the energy not only remains high but escalates. It's music that doesn't just want you to dance; it compels you, with every fiber of its being, to dance all night long.`,
  creator: "bitsong1qq6xd9qem3f345jlsszuvp5ese0cv2wje5cgyn",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/Qme5hbrEdciQdzoxaZ6mrsPbNcg843zbd7cuqx6cb5HMTe",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmY9Qe1VUTjnvrXNAqeH3YV564STJ3HogWM1EQfe5G1Bn8",
  startTime: 1707933600,
  genre: "House",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong10t2y7f9m0twpsrz3kvfp55nlgzc86kace2se3uarkv380h3pk6qqtkt9p7",
  marketplaceAddress: "bitsong1etp6acwkfv8kkuurskdepw8aqdwau5gnhjn88nfv5j6zgajdt7lqcdmxqa"
}, {
  id: '14',
  title: "14",
  artists: ["Puro Lobo"],
  description: `Dive into a whirlwind of words and compelling rhythms with '14', the debut single extracted from the EP 'PuroLobo' by the talented Roman rapper, Puro Lobo. This track leaves no room for breath, with an insistent rhythm that captures the listener's attention from the very first beat. Through its penetrating lyrics, Puro Lobo addresses the struggles faced by young people dealing with addictions, left to fend for themselves in a world where institutions offer scant assistance and a society increasingly indifferent to their hardships. '14' is a cry of anger and frustration against a system that seems to turn its back on the most vulnerable, a work that pushes the listener to reflect on the challenges faced by the new generations.`,
  creator: "bitsong1kttnxt84q5lzx9vhv5wls8f74u445uwg83c4g3",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmYf9JweethyFitJMZ5bV5icEr2Xk9Xq6UTnaqmefBt3qe",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmQ7rFzs8wbuvJxMb6AYDUHT6mVFtz6cMweo9pE5Hg3MZw",
  startTime: 1707847200,
  genre: "Hip Hop",
  explicit: "Explicit",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong1r57m20afwdhkwy67520p8vzdchzecesmlmc8k8w2z7t3h9aevjvseq4k7r",
  marketplaceAddress: "bitsong1vc4ltgpv8qkqkvgvup6hvpp49lkaswrmvzf0fausrnvchjr9z8dq3r06ex"
}, {
  id: 'perrea',
  title: "Perrea",
  artists: ["Joe Bertè"],
  description: `"Perrea" in spanish means 'twerk'. The track is a sun-soaked fusion of Latin-EDM, bursting with the zest of reggaeton's pulsating rhythms. It opens with the strumming of a guitar, its notes warm and inviting, conjuring images of a tropical paradise. This melody is the golden hour of the song, setting the scene for an escape to an endless summer. The vocal line dances over the track, a melodic embodiment of freedom and joy. The lyrics are an ode to the carefree ecstasy of summertime revelry, celebrating the here and now. The instrumental builds with an impetuous energy, each beat a heartbeat pushing you closer to the dance floor. The reggaeton influence is undeniable, with its signature dembow rhythm acting as the backbone of the track, urging you to move with abandon. The blend of EDM's electronic dynamism with the organic sounds of Latin music creates a track that is both contemporary and timeless.`,
  creator: "bitsong13ddj7ak2f8x6vetv67hrufsnz0ghr3e0s8c24u",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmPqSf9dEzpkVNWx4o6E5M4sVG4ea2EG7f6EE6BL2zza5S",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmbfyAeFNxMFBtBP6UrxRTEe8oKjJeNSiEsJ7RZ1otgcjA",
  startTime: 1707760800,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong1cvt7dz7fhhuhh8qrzjnq6uel4wnpswt5uq7d97kg4sh99dlrehds54w5t8",
  marketplaceAddress: "bitsong1e7sgpxr50rlxarvjt07n0pxgxre5fcgannucx37309446x5pwacstaghta"
}, {
  id: 'i-will-never-see-you-again',
  title: "I Will Never See You Again",
  artists: ["A.way"],
  description: `We are SINFUL MAZE Recordings, a group of producers originating from the Czech Republic, and over the past 5 years, we've expanded our influence worldwide. 

  The future has arrived! 
  
  Martin, a talented and industrious Slovak producer also known as A.way, is introducing our debut on SINFUL MAZE Bitsong in this distinctive competition with a delightful House track titled "I Will Never See You Again".`,
  creator: "bitsong19svnd02l742vx275sqruhan3aeayd92phv2y38",
  sellerFeeBps: 500,
  referralFeeBps: 70,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmXxzQnXJjTVoKVLobx8U8cqFiYKCgEnPdW2JpcWUqj9LG",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmY1FVpeTN4BcZuR8wR5jSN1XN3gQZNLWWg6Qo6ACLqxHx",
  startTime: 1707501600,
  genre: "House",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong1lj48z799hq4hgzg6ppdzsq55h6cezfe0cmrnnv7cclkpw9qrvf9sj4u92l",
  marketplaceAddress: "bitsong1dtaqwlmzlk3jku5un6h6rfunttmwsqnfz7evvdf4pwr0wypsl68qkwrf5n"
}, {
  id: 'sing-for-me',
  title: "Sing For Me",
  artists: ["Anirbas"],
  description: `"Sing for Me" weaves a tapestry of romantic sentiments with its dreamy, melodic voice that floats ethereally over a bed of rhythmic instrumentals. As the chorus approaches, there's a palpable sense of anticipation, like the moment before a sunrise. And then, with an exhilarating rush, the powerful EDM drop cascades over the senses, an electrifying blend of synth and bass that pulses through the body. The essence of "Sing for Me" lies in its ability to transport the listener to a space where love is both a quiet whisper and a triumphant shout, all encapsulated within a melody that lingers long after the final note has faded.`,
  creator: "bitsong1ruk3eu4zeplywxflg4jh3ggzp76r2dvq5yaudn",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/Qma8B5CGDHzuMebDrrPhYbFRLbkfrERAitBhDwrvfzUsrP",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmZXSzWNcx6WFB4FSsHURzrPge1pyiJEstcH2haFgsgJyX",
  startTime: 1707328800,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong1hz3svgdhmv67lsqlduu0tcnd3f75c0xr0mu48l6ywuwlz43zssjqsm3f2z",
  marketplaceAddress: "bitsong10j648ftg2g8p5vhgsu5kzfh6d907vpkrn0a5l3qch479eqy2qssqcw3qst"
}, {
  id: 'next-level',
  title: "Next Level",
  artists: ["Florin Dumbraveanu"],
  description: `I'm thrilled to introduce you to my very first NFT, "Next Level," a captivating Deep House track that I poured my heart and soul into. 🎵 As the founder of 404 Deep Records, it's an honor to share this piece of my musical journey with you on BitSong Studio.

  With "Next Level," I invite you to join me on a voyage through pulsating rhythms, ethereal harmonies, and infectious grooves.  It's a testament to the endless possibilities of music and the boundless creativity that drives us forward.`,
  creator: "bitsong1mvqdh3mkc9vaqr5394tkkef08jcnndcernl54j",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "https://media-api.bitsong.studio/ipfs/QmfWLFes83cLmbKKrwXdVNbJR7YftsbJUmzqDNKs6jnvHB",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmWh6qGWacSv3VAVWyAKVirJqMXD7X8pUVPXTTjM9Fh1kA",
  startTime: 1707242400,
  genre: "House",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong1ypk8p7c82whs9xdja6ku7q6slzj8kvfwkgxnyeuevhtf03fteylqg2wymp",
  marketplaceAddress: "bitsong16jd56eylzgwr2jyx97wymajp7u5h9rdn9jqh0nkfm6jswec66qkqakjsq5"
}, {
  id: 'cubana',
  title: "Cubana",
  artists: ["BlackJack Records"],
  description: "The song is a summerish tune with an urban-latin vibe. It’s composed by Tulea BlackJack in BlackJack Records studios.\n\n\"Cubana\" is a musical journey that seamlessly blends the rich tapestry of Latin beats with the contemporary flair of urban music, resulting in a vibrant and infectious composition. From the first note, the song encapsulates the spirited essence of Havana's dynamic streets, where every corner echoes with the pulsating rhythms of life.",
  creator: "bitsong1w35ntzzkf7dugwlq5a6lhrrp2lkq6yamxk42he",
  sellerFeeBps: 500,
  referralFeeBps: 50,
  previewUrl: "",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmdijLzx2c43XnacBRLAB1rPCtkn4ePjKpfGMQZq2pfbZk",
  startTime: 1706968800,
  genre: "Latin",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong19jq6mj84cnt9p7sagjxqf8hxtczwc8wlpuwe4sh62w45aheseueststug5",
  marketplaceAddress: "bitsong1r4x3lvn20vpls2ammp4ch5z08nge6h77p43ktl04efptgqxgl0qs5nnrp8"
}, {
  id: 'toxic',
  title: "Toxic",
  artists: ["Rawanne"],
  description: "The song is composed by Rawanne, Tulea BlackJack, Triplo Max and Karo (Pink Elephant). It’s a dance song with oriental, and trap influences.\n\nRawanne's \"Toxic\" stands as a captivating dance masterpiece, skillfully intertwining oriental and trap influences to create a dynamic and innovative sonic experience.",
  creator: "bitsong194sk3wwncjvn0zc3sysuj3kfxaqyd4a85ks5ka",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmVhHxoj14UURWPJb1gNQh16cxA24oqJfzS7vZKS3qTpv7",
  startTime: 1706896800,
  genre: "Dance",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong16p5fm4qrpjpxd8f5wpt48fgyyd5c79q4n35fgvq7x2yks2lu8llq3kre6f",
  marketplaceAddress: "bitsong193dzcmy7lwuj4eda3zpwwt9ejal00xva0vawcvhgsyyp5cfh6jyqe3sath"
}, {
  id: 'orderly',
  title: "Orderly",
  artists: ["Alan Scarlato"],
  description: "Orderly Neatly, this last track produced by Alan Scarlato was a totally new and fresh creation, with sounds different from what he had been doing, a different genre (Future Bass).\n\nIt has a melancholic SAD melody combined with great EUPHORIA and MOTIVATION at the same time. It represents those moments of sadness that we often go through until we break with it and use it as fuel to move towards motivation and creation!\n\nIt is characterized by having great strength and energy from the beginning to the end of the track.",
  creator: "bitsong1ljvvxrw6cxz645mwg33gh5xny8ekwc0lsfzjsa",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmVkDir4MUf9jyJsR8uajSWpFouYYPQ2cSAeu9AeVdPU7S",
  startTime: 1706882400,
  genre: "Future Bass",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong12njsx22ne73swjqxxn5e7xtc2n95y2aw8r73cqdth0g86way24cq6f5az9",
  marketplaceAddress: "bitsong1xut80d09q0tgtch8p0z4k5f88d3uvt8cvtzm5h3tu3tsy4jk9xlsmj9wd5"
}, {
  id: 'stimulation-growth',
  title: "Stimulation Growth",
  artists: ["Goose Pärk"],
  description: "\"Stimulation Growth\" isn't just a song; it's a groundbreaking musical odyssey that ventures into the heart of the digital realm. It serves as an anthem for the decentralized dreamers, NFT enthusiasts, and blockchain believers. Let the beats of \"Stimulation Growth\" transport you to a world where technology and creativity unite, pushing the boundaries of what's possible in this new digital era.",
  creator: "bitsong13xknrd2t5d28w3rnkly2dx3yxdwr97vhqr4z5w",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmYLRV4zMcFoREqaxNucwMBxWuNsZ1vKiNWmqYYP65ku8C",
  startTime: 1706882400,
  genre: "Hip-Hop",
  explicit: "Explicit",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong18a0pvw326fydfdat5tzyf4t8lhz0v6fyfaujpeg07fwqkygcxejsv0vqlr",
  marketplaceAddress: "bitsong1nwp0ynjv84wxysf2f5ctvysl6dpm8ngm70hss6jeqt8q7e7u345svel3d8"
}, {
  id: 'amnesia',
  title: "Amnesia",
  artists: ["Exept"],
  description: "Delta9 Recordings debuts officially with its first NFT and it's a huge track by Italian duo Exept together with a futuristic artwork created by label's visual master Kodin!\n\nMarco and Michele boasts considerable international music experience with releases on Drum&Bass top labels such as Vision, Invisible, Blackout and of course Delta9 Recordings!\n\nWith \"Amnesia\", the duo introduce you to the overall energy of this project which will provide you heavy beats surrounded with some sick dystopic tunes to recreate the environment the Italian duo belongs to.\n\nBe ready to be submerged by the immense transformative environment this NFT will create around you during its listening.\n\nThis is not music, but an incredible futuristic piece of digital art which will drive you in a vortex of emotions you can't deal with!",
  creator: "bitsong1dhez4sa0r4k0nvpctx5kddux9ztthlwgnkv97d",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmYWrmVQnEYL317cZbsAH9wv6eJihbdpxjPDyLtbotR2Zq",
  startTime: 1706637600,
  genre: "Drum & Bass",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong1nwnejwsdpqktusvh8qhxe5arsznjd5asdwutmaz9n5qcpl3dcmhswz930x",
  marketplaceAddress: "bitsong1w798gp0zqv3s9hjl3jlnwxtwhykga6rn93p46q2crsdqhaj3y4gs5az9k6"
}, {
  id: 'ready-or-not',
  title: "Ready or Not",
  artists: ["Adam Clay"],
  description: "**Ready or not** is absolutely the first **Music NFT released by Adam Clay** exclusively for **BitSong**.\n\nThe graphic concept is inspired by one of his most iconic photos, immersed in an unknown and vibrant universe, embracing the central concept of the song: diving into that incredible and mysterious journey that is life because only by facing the path will we be able to discover what awaits us along the way. \n\nAs for the musical aspect, the song, composed in collaboration with two well known Italian producers, **Paolo Sandrini** and **Eugenio Ferrara**, is a track with progressive house sounds, that unfolds like a cosmic journey; its energetic beats and ethereal sounds seemingly emanating from another dimension. At its core is a mantra, a lyrical repetition that echoes throughout the song, becoming a rallying cry for the listener.\n\nThe words, delivered with warmth by **Adam Clay's voice**, carry a profound message of **hope and liberation**. As the music builds, the mantra gains intensity, reinforcing its transformative power.\n\nThe combination of the hypnotic repetition, the dynamic progression of the house beats, and the evocative sounds from beyond infuse the track with a unique energy. It's a musical paradox—dark yet uplifting, grounding yet transcendent, and ultimately a sonic journey that invites the listener to embrace the unknown with open arms.",
  creator: "bitsong1f5ze3svwg8fgjuwwnr743j6fr9vtyr58nex7tu",
  sellerFeeBps: 500,
  referralFeeBps: 100,
  previewUrl: "",
  artworkUrl: "https://media-api.bitsong.studio/ipfs/QmWF5LpGkH67fqv89cTrB36UAcxo2ZtbY9VSMv7wKKaAoQ",
  startTime: 1706205600,
  genre: "House",
  explicit: "Clean",
  license: "All Rights Reserved",
  initialPrice: 0.018,
  nftAddress: "bitsong1wl59k23zngj34l7d42y9yltask7rjlnxgccawc7ltrknp6n52fpsepyxgg",
  marketplaceAddress: "bitsong1kj8q8g2pmhnagmfepp9jh9g2mda7gzd0m5zdq0s08ulvac8ck4dqalzxgv"
}]

export function getTrackById(id: string): Track | undefined {
  return tracks.find(track => track.id === id);
}

export function getAllTracks(): Track[] {
  return tracks;
}

interface Drop {
  id: string;
  image: string;
  subtitle: string;
  title: string;
  startTime: number;
  link: string;
}

export function getUpcomingDrops(): Drop[] {
  const drops = tracks.filter(drop => drop.startTime > Math.floor(Date.now() / 1000))
    .sort((a, b) => a.startTime - b.startTime)

  return drops.map(drop => ({
    id: drop.id,
    image: drop.artworkUrl,
    subtitle: drop.artists.join(", "),
    title: drop.title,
    startTime: drop.startTime,
    link: `/preview/${drop.id}`
  }))
}

export function getFeaturedDrops(): Drop[] {
  const drops = tracks.filter(drop => drop.startTime < Math.floor(Date.now() / 1000))
    .sort((a, b) => b.startTime - a.startTime)

  return drops.map(drop => ({
    id: drop.id,
    image: drop.artworkUrl,
    subtitle: drop.artists.join(", "),
    title: drop.title,
    startTime: drop.startTime,
    link: `/nfts/${drop.nftAddress}`
  }))
}